// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcV3Ngn68Bed101nWNHJ3GmevByLDEO1w',
    appId: '1:802667688232:web:1b0cfa9da545a87055e01d',
    messagingSenderId: '802667688232',
    projectId: 'picsorter-1',
    authDomain: 'picsorter-1.firebaseapp.com',
    storageBucket: 'picsorter-1.firebasestorage.app',
    measurementId: 'G-DQXTKVYZJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GyC5kg9qRCsjKBVqEf6kR5hflRolyUU',
    appId: '1:802667688232:android:4dc77214f0a032c955e01d',
    messagingSenderId: '802667688232',
    projectId: 'picsorter-1',
    storageBucket: 'picsorter-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajfRJvHL_3hOIWdIsUH07fvGvfI_79OI',
    appId: '1:802667688232:ios:d47236f692f75c5055e01d',
    messagingSenderId: '802667688232',
    projectId: 'picsorter-1',
    storageBucket: 'picsorter-1.firebasestorage.app',
    iosBundleId: 'com.example.picsorter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajfRJvHL_3hOIWdIsUH07fvGvfI_79OI',
    appId: '1:802667688232:ios:d47236f692f75c5055e01d',
    messagingSenderId: '802667688232',
    projectId: 'picsorter-1',
    storageBucket: 'picsorter-1.firebasestorage.app',
    iosBundleId: 'com.example.picsorter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcV3Ngn68Bed101nWNHJ3GmevByLDEO1w',
    appId: '1:802667688232:web:dcc3da7850a2ebf855e01d',
    messagingSenderId: '802667688232',
    projectId: 'picsorter-1',
    authDomain: 'picsorter-1.firebaseapp.com',
    storageBucket: 'picsorter-1.firebasestorage.app',
    measurementId: 'G-WGG4RP3K89',
  );
}
